### Importing Modules

In [1]:
import tensorflow as tf
from tensorflow import keras

import pandas as pd
import numpy as np

### Data Importing

In [2]:
x1 = pd.read_csv("Data1.csv")
x2 = pd.read_csv("Data2.csv")

In [3]:
y1 = np.zeros((200, 1))
y2 = np.ones((200, 1))
y_train = np.concatenate((y1[:180], y2[:180]))
y_test = np.concatenate((y1[180:], y2[180:]))

In [4]:
y_train

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

### Data Preprocessing

In [5]:
def convert(x):
    branch = {
        "AI":0,
        "DS":1,
        "CS":2, 
        "IT":3,
        "ECE":4,
        "CE":5,
        "ME":6,
        "EE":7
    }
    cat = {
        "SC":0,
        "ST":1,
        "GEN":2,
        "GEN-EWS":3,
        "OBC":4,
        "PWD":5,
        "EX-SER":6,
        "KM":7,
        "PH":8,
        "SBC":9,
        "MIN":10
    }
    state = {
        "Home State":0,
        "Other State":1
    }
    for n, i in enumerate(x):
        x[n][0] = (branch[x[n][0]]/7)
        x[n][1] = (cat[x[n][1]]/10)
        x[n][2] = state[x[n][2]]
        x[n][3] = x[n][3]/100
        x[n][4] = x[n][4]/100

    return x

x1 = x1.to_numpy()
x1 = convert(x1)
x2 = x2.to_numpy()
x2 = convert(x2)

x1 = x1.astype(np.float64)
x2 = x2.astype(np.float64)
x_train = np.concatenate((x1[:180], x2[:180]))
x_test = np.concatenate((x1[180:], x2[180:]))

In [6]:
x_train

array([[0.71428571, 0.        , 1.        , 0.9       , 0.88      ],
       [0.85714286, 0.1       , 1.        , 0.99      , 0.88      ],
       [0.        , 1.        , 1.        , 1.        , 0.91      ],
       ...,
       [0.        , 0.        , 1.        , 0.71      , 0.62      ],
       [0.28571429, 0.9       , 0.        , 0.8       , 0.63      ],
       [0.        , 0.8       , 1.        , 0.88      , 0.62      ]])

### Creating Model

In [7]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=((5, ))),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(2, activation='softmax')
])

### Compiling Model

In [8]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

### Fitting Data

In [17]:
model.fit(tf.convert_to_tensor(x_train), tf.convert_to_tensor(y_train), epochs=5)

Epoch 1/5
12/12 [==============================] - 0s 3ms/step - loss: 0.6409 - accuracy: 0.6722
Epoch 2/5
12/12 [==============================] - 0s 5ms/step - loss: 0.6321 - accuracy: 0.7000
Epoch 3/5
12/12 [==============================] - 0s 4ms/step - loss: 0.6353 - accuracy: 0.6583
Epoch 4/5
12/12 [==============================] - 0s 4ms/step - loss: 0.6258 - accuracy: 0.7222
Epoch 5/5
12/12 [==============================] - 0s 4ms/step - loss: 0.6196 - accuracy: 0.7222


### Evaluating Model

In [18]:
test_loss, test_acc = model.evaluate(tf.convert_to_tensor(x_test), tf.convert_to_tensor(y_test))
print('Test accuracy:', test_acc)

2/2 [==============================] - 0s 4ms/step - loss: 0.6011 - accuracy: 0.7500
Test accuracy: 0.75


### Making Predictions

In [19]:
predictions = model.predict(x_test[10:30])

print(y_test[10:30])
print(predictions)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0.57191133 0.4280887 ]
 [0.5633758  0.43662417]
 [0.5175812  0.48241878]
 [0.5601477  0.43985233]
 [0.55298346 0.44701657]
 [0.70370024 0.2962998 ]
 [0.6311084  0.36889163]
 [0.4934732  0.5065268 ]
 [0.513159   0.48684102]
 [0.64965963 0.35034037]
 [0.5546078  0.44539225]
 [0.40848362 0.5915164 ]
 [0.45492697 0.5450731 ]
 [0.5053401  0.49465993]
 [0.3333961  0.66660386]
 [0.5544859  0.44551405]
 [0.47494823 0.52505183]
 [0.56456554 0.43543455]
 [0.5990725  0.4009275 ]
 [0.423572   0.576428  ]]
